auto: true
server: true
pygments: true
permalink: /:categories/:year/:month/:day/:title/
root_dir: "http://blagobutik.ru"
baseurl: "http://blagobutik.ru"
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md

prose:
  metadata: 
    _posts/news: |
      layout: news
      title: Your Post Title
      subtitle:
      category: news
      published: true